overwrite: true
schema: 'schema.json'
documents: 'src/**/*.graphql'
generates:
  src/graphql/generated/index.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
